# -*- coding: utf-8 -*-
"""PRODIGY_TASK3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vKbSxV5uZyLCA_FD5_bNQqCd83Fbq_rc
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.tree import plot_tree

# Step 1: Load the dataset
data=pd.read_csv('bank-additional-full.csv',sep=';')
data.head()

label_encoders = {}
for col in data.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

print("\nEncoded Columns:", list(label_encoders.keys()))

X = data.drop("y", axis=1)
y = data["y"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


model = DecisionTreeClassifier(criterion="entropy", max_depth=5, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\n Model Evaluation")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

plt.figure(figsize=(6,4))
sns.countplot(x=y, palette="Set2")
plt.title("Data Distribution (Subscribed vs Not Subscribed)")
plt.show()
plt.savefig("data_distribution.png")
plt.close()

plt.figure(figsize=(6,4))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()
plt.savefig("confusion_matrix.png")
plt.close()

importances = model.feature_importances_
features = X.columns

plt.figure(figsize=(10,6))
sns.barplot(x=importances, y=features, palette="viridis")
plt.title("Feature Importance in Decision Tree")
plt.show()
plt.savefig("feature_importance.png")
plt.close()

plt.figure(figsize=(18,10))
plot_tree(model, feature_names=features, class_names=["No", "Yes"], filled=True, fontsize=8)
plt.show()
plt.savefig("decision_tree_plot.png")
plt.close()

