# -*- coding: utf-8 -*-
"""PRODIGY_TASK1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b8gOtTtGMy82rHIWJleLJJGu0aXCKo7r
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv('/content/Metadata_Country_API_SP.POP.TOTL_DS2_en_csv_v2_38144.csv')
data.head()

region_counts=data["Region"].fillna("Unknown").value_counts()
plt.figure(figsize=(20,6))

plt.subplot(1,2,1)
plt.bar(region_counts.index,region_counts.values)

plt.xlabel("IncomeGroup")
plt.ylabel("Count")
plt.title("Region Counts")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

income_counts=data["IncomeGroup"].fillna("Unknown").value_counts()

plt.subplot(1,2,2)
plt.bar(income_counts.index,income_counts.values)

plt.xlabel("IncomeGroup")
plt.ylabel("Count")
plt.title("Income Group Counts")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()