# -*- coding: utf-8 -*-
"""PRODIGY_TASK2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZaQI4k253HJ4mexuqyUNQavg9bW5dE-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv('Titanic-Dataset.csv')
data.head()

data.describe()

data.info()

data.isnull().sum()

data.dropna(subset=["Embarked"], inplace=True)
data["Cabin"].fillna("Unknown", inplace=True)
data["Age"].fillna(data["Age"].mean(), inplace=True)
data.isnull().sum()

print("Relation of Survival with other variables")
plt.figure(figsize=(8, 4))
sns.countplot(x="Survived", hue="Sex", data=data)
plt.title("Survival by Sex")
plt.show()

plt.figure(figsize=(8, 4))
sns.histplot(data=data, x='Age', kde=True, hue='Survived', common_norm=False)
plt.title("Survival by Age")
plt.show()

plt.figure(figsize=(8, 4))
sns.countplot(x="Survived", hue="Pclass", data=data)
plt.title("Survival by Passenger Class")
plt.show()

plt.figure(figsize=(10, 6))
correlation_matrix = data[['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(8, 4))
sns.histplot(data=data, x='Age', kde=True, bins=20)
plt.title("Age Distribution")
plt.show()